sodaflow:
  dataset_path:
    - "/datasets/kaflix-part-dataset"
  start_ckpt_path: "./trained_model"
  test_model_path: "./trained_model"

train_inputs:
  TRAIN_EPOCHS: 5
  STEPS_PER_EPOCH: 500
  VALIDATION_STEPS: 100

  LEARNING_RATE: 1e-04
  NUM_CLASSES: 28
  IMAGE_MIN_DIM: 832
  IMAGE_MAX_DIM: 832
  USE_MINI_MASK: false
  MAX_GT_INSTANCES: 30

  POST_NMS_ROIS_TRAINING: 3000
  POST_NMS_ROIS_INFERENCE: 3000

  ROI_POSITIVE_RATIO: 0.5
  TRAIN_ROIS_PER_IMAGE: 512
  RPN_TRAIN_ANCHORS_PER_IMAGE: 512

  FLIP: [false,true]
  BRIGHT: [0.8, 1, 1.2]
  ROTATION: [-10, 0, 10]

  IMAGES_PER_GPU: 1
  GPU_IDS: "0"
  BACKBONE: resnet50

  FROM_BEGINNING: False

  DETECTION_MIN_CONFIDENCE: 0.9
  DETECTION_NMS_THRESHOLD: 0.4

  FLITERING_MASK_SIZE: True
  FOCUS_RULE: True
  FOCUS_BOX_SIZE: [240,320]

MODEL_TYPE: ""
MODEL_NAME: resnet50
NAME: car
MODEL_DIR: "./logs"
LOGS_DIR: "./logs"
IMAGE_RESIZE_MODE: square

EVAL_RESULT_IMAGE_SAVE: True
EVAL_SAVE_PATH: "./eval_results"
